// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("dotnet-drama.Tests")>]
[<assembly: AssemblyProductAttribute("dotnet-drama")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-10-23T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","837c2512fa65b5349ee4db858b39d4573de17744")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "dotnet-drama.Tests"
    let [<Literal>] AssemblyProduct = "dotnet-drama"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-10-23T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "837c2512fa65b5349ee4db858b39d4573de17744"
